# SPDX-FileCopyrightText: 2024 Alexandre Jesus <me@adbjesus.com>
#
# SPDX-License-Identifier: Apache-2.0

repos:
-   repo: https://github.com/fsfe/reuse-tool
    rev: v6.1.2
    hooks:
    - id: reuse
-   repo: https://github.com/DavidAnson/markdownlint-cli2 
    rev: v0.18.1
    hooks:
    - id: markdownlint-cli2
